let token=localStorage.getItem('maheer-admin');const $=s=>document.querySelector(s);function auth(){return{Authorization:'Bearer '+token,'Content-Type':'application/json'}}function show(){if(token){$('#login').classList.add('hidden');$('#app').classList.remove('hidden');loadDashboard()}}
async function login(){const r=await fetch('/api/admin/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password:$('#pass').value})});const j=await r.json();if(j.token){token=j.token;localStorage.setItem('maheer-admin',token);show()}else $('#err').textContent=j.error||'Login failed'}function logout(){localStorage.removeItem('maheer-admin');location.reload()}
function toggleSidebar(force){const s=$('#sidebar'),open=force===undefined?!s.classList.contains('open'):force;s.classList.toggle('open',open);$('#adminBackdrop').classList.toggle('hidden',!open)}
function tab(id){document.querySelectorAll('.tab').forEach(x=>x.classList.add('hidden'));$('#'+id).classList.remove('hidden');document.querySelectorAll('.sideItem').forEach(x=>x.classList.toggle('active',x.dataset.tab===id));/* Sidebar intentionally stays open after navigation on mobile. */if(id==='products')loadProducts();if(id==='orders')loadOrders();if(id==='settings')loadSettings();}
async function getJson(url,opt={}){const r=await fetch(url,opt);if(r.status===401){logout();return []}return r.json()}
async function loadDashboard(){const p=await getJson('/api/admin/products',{headers:auth()});const o=await getJson('/api/admin/orders',{headers:auth()});$('#pc').textContent=p.length;$('#oc').textContent=o.length;$('#rev').textContent='৳'+o.reduce((s,x)=>s+Number(x.total||0),0).toLocaleString('en-BD')}
async function loadProducts(){const p=await getJson('/api/admin/products',{headers:auth()});$('#productTable').innerHTML=`<div class="tableWrap"><table><tr><th>IMAGE</th><th>NAME</th><th>CATEGORY</th><th>PRICE</th><th>STOCK</th><th>ACTION</th></tr>${p.map(x=>`<tr><td><img class="thumb" src="${x.image}" alt=""></td><td>${esc(x.name)}</td><td>${esc(x.category)}</td><td>৳${Number(x.price).toLocaleString('en-BD')}</td><td>${x.stock}</td><td><button class="mini" onclick='editProduct(${JSON.stringify(x).replace(/</g,'\\u003c')})'>Edit</button> <button class="mini" onclick='deleteProduct(${x.id})'>Delete</button></td></tr>`).join('')}</table></div>`}
function esc(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function openProductForm(){ $('#modal').classList.remove('hidden');$('#productForm').reset();$('#productForm [name=id]').value='';$('#formTitle').textContent='Add Product';toggleSidebar(false)}function closeForm(){$('#modal').classList.add('hidden');}
function editProduct(p){openProductForm();$('#formTitle').textContent='Edit Product';for(const k of ['id','name','category','price','image','description','stock'])$('#productForm [name='+k+']').value=p[k]??'';$('#productForm [name=featured]').checked=!!p.featured}
async function deleteProduct(id){if(!confirm('Delete this product?'))return;await fetch('/api/admin/products/'+id,{method:'DELETE',headers:auth()});loadProducts();loadDashboard()}
$('#productForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);let image=f.get('image');const file=$('#file').files[0];if(file){const fd=new FormData();fd.append('image',file);const u=await fetch('/api/admin/upload',{method:'POST',headers:{Authorization:'Bearer '+token},body:fd}).then(r=>r.json());if(u.url)image=u.url}const body={name:f.get('name'),category:f.get('category'),price:f.get('price'),image,description:f.get('description'),stock:f.get('stock'),featured:f.get('featured')==='on'};const id=f.get('id');await fetch('/api/admin/products'+(id?'/'+id:''),{method:id?'PUT':'POST',headers:auth(),body:JSON.stringify(body)});closeForm();loadProducts();loadDashboard()};
async function loadOrders(){const o=await getJson('/api/admin/orders',{headers:auth()});$('#orderTable').innerHTML=`<div class="tableWrap"><table><tr><th>ORDER</th><th>CUSTOMER</th><th>PHONE</th><th>TOTAL</th><th>STATUS</th><th>DATE</th></tr>${o.map(x=>`<tr><td><b>${esc(x.order_no)}</b></td><td>${esc(x.name)}</td><td>${esc(x.phone)}</td><td>৳${Number(x.total||0).toLocaleString('en-BD')}</td><td><select onchange="status(${x.id},this.value)"><option ${x.status==='Pending'?'selected':''}>Pending</option><option ${x.status==='Confirmed'?'selected':''}>Confirmed</option><option ${x.status==='Processing'?'selected':''}>Processing</option><option ${x.status==='Shipped'?'selected':''}>Shipped</option><option ${x.status==='Delivered'?'selected':''}>Delivered</option><option ${x.status==='Cancelled'?'selected':''}>Cancelled</option></select></td><td>${new Date(x.created_at||Date.now()).toLocaleString()}</td></tr>`).join('')}</table></div>`}async function status(id,v){await fetch('/api/admin/orders/'+id,{method:'PUT',headers:auth(),body:JSON.stringify({status:v})})}
async function loadSettings(){const s=await fetch('/api/settings').then(r=>r.json());for(const k of ['about','phone','whatsapp','email','facebook','instagram','tiktok','youtube'])$('#settingsForm [name='+k+']').value=s[k]||''}$('#settingsForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);const body=Object.fromEntries(f.entries());await fetch('/api/admin/settings',{method:'PUT',headers:auth(),body:JSON.stringify(body)});alert('Settings saved ✓')};show();
